### ISSUE TITLE
Migration to Node 10

### ISSUE THREAD

**Issue by azmijewski-dc** [Genetec/azure-devops-extension-publishtestresultscreenshot#14]
This task uses Node 6 execution handler, which will be removed March 31st 2022

Please migrate this addon to Node 10.

**Comment by kjgen** [comment]
Closing issue because the extension is being deprecated and will no longer be maintained. An alternative solution is to use the Publish Test Result task which now supports
[file attachments](https://devblogs.microsoft.com/devops/junit-attachments-support-for-publish-test-results/).
