### ISSUE TITLE
Adding Support for Azure Devops On Premises

### ISSUE THREAD

**Issue by PixelShober** [Genetec/azure-devops-extension-publishtestresultscreenshot#16]
Dear Developer Team,
would it be possible to release this extension for on premise maschines? Or is there a way to achieve this? 
I would love to use the functionality of your extension for our enviroment to optimize our testing! 

Best regards!

**Comment by kjgen** [comment]
Closing issue because the extension is being deprecated and will no longer be maintained. An alternative solution is to use the Publish Test Result task which now supports
[file attachments](https://devblogs.microsoft.com/devops/junit-attachments-support-for-publish-test-results/).
