### ISSUE TITLE
Publish screenshot with different name from testname

### ISSUE THREAD

**Issue by mrodi** [Genetec/azure-devops-extension-publishtestresultscreenshot#21]
Hi!
I would like to upload .png files with random name, but task search only files with same name.
![image](https://github.com/Genetec/azure-devops-extension-publishtestresultscreenshot/assets/43407762/49f0edd9-a333-4e06-9344-5a11d8cd364a)
![image](https://github.com/Genetec/azure-devops-extension-publishtestresultscreenshot/assets/43407762/3b17253e-320b-4868-ae9f-1f8dddbd7079)

**Comment by kjgen** [comment]
Closing issue because the extension is being deprecated and will no longer be maintained. An alternative solution is to use the Publish Test Result task which now supports
[file attachments](https://devblogs.microsoft.com/devops/junit-attachments-support-for-publish-test-results/).
