### ISSUE TITLE
Issues block mapping and emulator image

### ISSUE THREAD

**Issue by PhilipChr** [Genetec/azure-devops-extension-publishtestresultscreenshot#5]
Good evening, 
I would like to thank you in advance and I would position this as a starter question. I refer to the medium blog entry and I tried to solve it already by myself with your documentation. 

I have integrated a UnitTest into my current project. Now I would be very happy if I could use your program in Azure. You can find the YAML file in the appendix. First I had the following problem when I didn't use your Python script but your "Screenshot Task". Encountered error(s) while parsing pipeline YAML:
/azure-pipelinesUITest.yml: (Line: 47, Col: 1, Idx: 2029) - (Line: 47, Col: 2, Idx: 2030): While parsing a block mapping, did not find expected key.

Line 47 is the beggining of the task. 
![grafik](https://user-images.githubusercontent.com/56686963/99566400-22929b80-29cd-11eb-9bd3-48d277f7e13c.png)
continueOnError: true

If I exclude this task there is another problem with downloading and installing the emulator image. 
![grafik](https://user-images.githubusercontent.com/56686963/99566218-e4957780-29cc-11eb-96f1-f838c917c31f.png)

Thank you so much!

**Comment by eric-labelle** [comment]
Hi! First of, to solve the emulator error is quite easy. 

So, for the emulator, you can refer to [android issue](https://issuetracker.google.com/issues/155847875). Turns out they removed this image from sdk, not sure why yet the google-api version of this 28 API images has been removed, but I had swapped to `system-images;android-28;default;x86` a few months back when I noticed they had removed it.

Your other problems seems to simply be a formatting error based on your screenshot.  The `-task:` nodes needs to be aligned always, otherwise your YAML won't be parsed properly.

i.e.
```
- task: PublishTestResults@2
- task: Genetec.publish-test-result-screenshot.pipeline-extension.PublishTestResultScreenshot@0
```

Thanks

**Comment by PhilipDiePython** [comment]
Thank you so much! This helped me a lot! 
Maybe u can refer to your own project. Also I hope solving this problem for other users, 
![grafik](https://user-images.githubusercontent.com/56686963/99662559-b748d800-2a65-11eb-9276-b4c258344ea6.png)
You use the "system-images;android-28;default;x86" ?
I read about the android issue and had the issue that there is no emulator in this directory
![grafik](https://user-images.githubusercontent.com/56686963/99662893-26263100-2a66-11eb-9aaf-d6b225a08982.png)
Thank you in advance. 

(Thank you for supporting "noobs" :)"
Kind regards 
Philip

**Comment by PhilipChr** [comment]
Hello, thank you for your fast answer 👍 
I use the emulator described over here https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops 
It will install "system-images;android-27;google_apis;x86" and this works absolutely fine!
There is "another" I hope the last issue .. 
During the Instrumented tests is a permission denied error. I would be grateful for help. 
![grafik](https://user-images.githubusercontent.com/56686963/99668178-aac87d80-2a6d-11eb-9394-d1c1efd60bc0.png)
Just for your information the full yaml:
![grafik](https://user-images.githubusercontent.com/56686963/99668255-c92e7900-2a6d-11eb-8ba2-762154b31b7a.png)

**Comment by eric-labelle** [comment]
I think your problem is that you replaced the systemimage when creating the AVD, but not when you download and install the systemimage in the previous step.

```
echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-28;default;x86'
echo "==============> Image downloaded (system-images;android-28;default;x86)"
```

I chose 28:default for my usecase, but you are free to choose the version you want if you prefer to test on API29, 30 or 23 or whichever. There is plenty to chose from.

You can find all available system-images using the following command
```
$ANDROID_HOME/tools/bin/sdkmanager --list | grep system-images
```

**Comment by PhilipChr** [comment]
The Image is working fine 🥇  Changed to version 28 because of your tipp. 
![grafik](https://user-images.githubusercontent.com/56686963/99672320-866f9f80-2a73-11eb-8530-9ec964869afa.png)
As described above there is the permission denied error
![grafik](https://user-images.githubusercontent.com/56686963/99672476-bfa80f80-2a73-11eb-9634-f2b66577da84.png)
Afterwards there are no tests available, i think this is the result because of the permission denied error. 
![grafik](https://user-images.githubusercontent.com/56686963/99672530-cfbfef00-2a73-11eb-8781-0154b287f363.png)
Screenshots of my tests:
![grafik](https://user-images.githubusercontent.com/56686963/99672611-e9f9cd00-2a73-11eb-9589-efd1b026b1ce.png)

Hopefully my questions are not too stupid 
Thanks! 
Philip
[yaml file.txt](https://github.com/Genetec/azure-devops-extension-publishtestresultscreenshot/files/5567042/yaml.file.txt)

**Comment by eric-labelle** [comment]
I remember facing this error at some point but not sure what it was. You can in the meantime replace the bash task by the provided gradle task
```
      - bash: |
          ./gradlew connectedDebugAndroidTest --console=plain  --stacktrace
          ./gradlew --stop
        displayName: 'Run Instrumented Tests'
        continueOnError: true
```
by
```
      - task: Gradle@2
        displayName: 'Run Instrumented Tests'
        inputs:
          tasks: 'connectedDebugAndroidTest --console=plain  --stacktrace'
          publishJUnitResults: false
        continueOnError: true
```

**Comment by PhilipChr** [comment]
NOW ITS WORKING. I am excited 😄. Atleast I know if there is an error in the UITest, so I do have a response. The Screenshot is a nice to have. 
Finally I am moving forward to the screenshot section. 
The pipeline is somehow skipping the task, there is no error response or something similiar. 

I tried the execution with a test (including error) and a passing. 
All tests passed: 
![grafik](https://user-images.githubusercontent.com/56686963/99694622-ecb4ec00-2a8c-11eb-80bb-f87b0328eb9e.png)
![grafik](https://user-images.githubusercontent.com/56686963/99694718-00605280-2a8d-11eb-9276-7a3635dc50d4.png)

An error in the test:
![grafik](https://user-images.githubusercontent.com/56686963/99694817-1b32c700-2a8d-11eb-8373-8c3c606d86a2.png)
![grafik](https://user-images.githubusercontent.com/56686963/99694867-284fb600-2a8d-11eb-96fa-439513529bbe.png)
![grafik](https://user-images.githubusercontent.com/56686963/99694891-300f5a80-2a8d-11eb-871a-9000d4e4fc53.png)

Greetings from Germany :)

**Comment by kjgen** [comment]
Closing issue because the extension is being deprecated and will no longer be maintained. An alternative solution is to use the Publish Test Result task which now supports
[file attachments](https://devblogs.microsoft.com/devops/junit-attachments-support-for-publish-test-results/).
