### ISSUE TITLE
Custom domain not supported

### ISSUE THREAD

**Issue by LuisOsv** [Genetec/azure-devops-extension-publishtestresultscreenshot#8]
**Agent pool:** [Private pool]
**Agent specification:** [windows]
**Context:** [ Web]
**Test result format:** [jUnit]

**Describe the bug**
It's not possible to use the task screenshots when using custom domain e.g.
https://custom.visualstudio.com instead of https://dev.azure.com

**To Reproduce**
1. Add the task Publish screenshots for test failure to the pipeline
2. Add custom domain in the Organization field e.g. https://custom.visualstudio.com/{organization}
3. Run the pipeline
![image](https://user-images.githubusercontent.com/1733890/109531191-f982ac00-7a8d-11eb-9fc0-e8b1d6827fbc.png)

**Comment by tyler-j-jackson** [comment]
@LuisOsv 
What's the output you're seeing? I'm getting the following:
`##[error]﻿{"$id":"1","innerException":null,"message":"A potentially dangerous Request.Path value was detected from the client (:).","typeName":"System.Web.HttpException, System.Web","typeKey":"HttpException","errorCode":0,"eventId":0}`

**Comment by kjgen** [comment]
Closing issue because the extension is being deprecated and will no longer be maintained. An alternative solution is to use the Publish Test Result task which now supports
[file attachments](https://devblogs.microsoft.com/devops/junit-attachments-support-for-publish-test-results/).
