### ISSUE TITLE
Plugin Not working

### ISSUE THREAD

**Issue by stefanbulzan** [Genetec/azure-devops-extension-publishtestresultscreenshot#9]
I configured my plugin to run on vsts
I've set the organization name and an existing folder containing png files
Result: ##[error]Cannot read property 'value' of null

**Comment by eric-labelle** [comment]
As mentioned in the readme, support is currently only for DevOps Cloud. 
See https://github.com/Genetec/azure-devops-extension-publishtestresultscreenshot/issues/1 for On Prem support
Thanks
